package gov.hawaii.digitalarchives.hida.core.model.record;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.slf4j.Logger;
import org.springbyexample.util.log.AutowiredLogger;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * An {@code Agent} is an entity that takes part in the creation or preservation
 * of a {@link DigitalRecord}.
 * 
 * @author Dongie Agnir
 */
@Configurable
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@Table(name = "AGENT")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
public class Agent implements Serializable {
    
    /**
     * Autogenerated for this entity to be serializable. Implementing
     * Serializable isn't strictly necessary as far as the JPA specification
     * is concerned. However, it is needed if you're going to use caching or
     * EJB remoting, both of which require objects to be Serializable.
     * Caching is a key component in achieving optimal performance in any
     * JPA application, so implementing the Serializable interface is a good
     * habit to adopt. Note: This was taken from the book titled, 
     * "Spring Persistence with Hibernate", 2010, Fisher and Murphy. 
     */
    private static final long serialVersionUID = 5044373369468419883L;

    /**
     * Primary id of an Agent class
     */
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column(name = "AGENT_ID")
    private Long primaryId;

    /**
     * Version of an Agent class.
     */
    @Version
    @Column(name = "VERSION")
    private Integer version;
    
    /**
     * Name of the Agent.
     */
    @Column(name = "NAME")
    private String name;

    /**
     * Agent's note.
     */
    @Column(name = "NOTE")
    private String note;
    
    /** Autowired logger to log this class */
    private transient Logger log = null;
    
    /**
     * Oracle specifications state that the class must have a public or
     * protected, no-argument constructor. The class may have other
     * constructors.
     * http://docs.oracle.com/javaee/7/tutorial/doc/persistence-intro001.htm
     */
    public Agent() {
        
    }

    /**
     * @return The name of this {@code Agent}.
     */
    public String getName() {
        log.debug("Exiting getName(): {}", name);
        return name;
    }

    /**
     * @return Any miscellaneous notes about this {@code Agent}.
     */
    public String getNote() {
        log.debug("Exiting getNote(): {}", note);
        return note;
    }
    
    /**
     * Creates a Agent and ensures that their fields are not null.
     * 
     * @param name  Agent's name.
     * @param note  Agent's note.
     */
    public Agent(final String name, final String note) {
        Assert.notNull(name, "name cannot be null");
        Assert.hasLength(name, "name cannot be empty");
        Assert.notNull(note, "note cannot be null");
        Assert.hasLength(note, "note cannot be empty");
        this.name = name;
        this.note = note;
    }

    /**
     * Assists in implementing Object.toString() methods using reflection. This
     * class uses reflection to determine the fields to append. Because these
     * fields are usually private, the class changes the visibility of the
     * fields. This will fail under a security manager, unless the appropriate
     * permissions are set up correctly.
     */
    @Override
    public String toString() {
        log.debug("Entering toString()");
        String toString = ReflectionToStringBuilder.toString(this,
                ToStringStyle.SHORT_PREFIX_STYLE);
        log.debug("Exiting toString(): {}", toString);
        return toString;
    }

    /**
     * An {@link EntityManager} instance is associated with a persistence
     * context. A persistence context is a set of entity instances in which for
     * any persistent entity identity there is a unique entity instance. Within
     * the persistence context,the entity instances and their life cycle are
     * managed. The EntityManager API is used to create and remove persistent
     * entity instances, to find entities by their primary key, and to query
     * over entities. As long as an object is attached to an EntityManager, all
     * changes to the object will be synchronized with the database
     * automatically (Meaning that this object is attached to the 'persistence
     * context').
     */
    @PersistenceContext
    transient EntityManager entityManager;

    /**
     * A new entity manager is created for every persistence related function. 
     * This pattern is called an “entitymanger-per-request” pattern. 
     * In this model, a request from the client is sent to the server 
     * (where the JPA persistence layer runs), a new EntityManager is opened, 
     * and all database operations are executed in this unit of work. Once the 
     * work has been completed (and the response for the client has been
     * prepared), the persistence context is flushed and closed, as well 
     * as the entity manager object. You would also use a single database 
     * transaction to serve the clients request. The relationship between 
     * the two is one-to-one and this model is a perfect fit for many 
     * applications.
     *  
     * http://docs.jboss.org/hibernate/entitymanager/
     *  
     * @return A new EntityManager to do database operations.
     */
    public static final EntityManager entityManager() {
        staticMethodLogger().debug("Entering entityManager()");
        EntityManager em = new Agent().entityManager;
        if (em == null)  {
            String errorMessage = "Entity manager has not been injected "
                    + "(is the Spring Aspects JAR configured as an AJC/AJDT aspects library?'";
            staticMethodLogger().error(errorMessage);
            throw new IllegalStateException(errorMessage);
        }
        
        staticMethodLogger().debug("Exiting entityManager(): {}", em);
        return em;
    }
    
    /**
     * Used to log static methods of this class. Since
     * Autowired logger cannot be "static", this method allows an 
     * Autowired Logger to be used within static methods.
     * 
     * @return A new logger to do logging operations.
     */
    protected static final Logger staticMethodLogger() {
        Logger log = new Agent().log;
        if (log == null) {
            throw new IllegalStateException("Logger has not been"
                    + " injected!");
        }
        return log;
    }

    /**
     * Gets the amount of Agent objects that are currently in the database.
     * 
     * @return The amount of Agent objects that are currently in the database.
     */
    public static long countAgents() {
        staticMethodLogger().debug("Entering countAgents()");
        long count = entityManager().createQuery("SELECT COUNT(o) FROM Agent o",
                Long.class).getSingleResult();
        staticMethodLogger().debug("Exiting countAgents(): {}", count);
        return count;
    }

    /**
     * Gets all of the Agent objects from the database and puts them in a
     * collection.
     * 
     * @return The collection of Agent objects that are in the database.
     */
    public static List<Agent> findAllAgents() {
        staticMethodLogger().debug("Entering findAllAgents()");
        List<Agent> agents = entityManager()
                .createQuery("SELECT o FROM Agent o", Agent.class)
                .getResultList();
        staticMethodLogger().debug("Exiting findAllAgents(): {}", agents);
        return agents;
    }

    /**
     * Gets an Agent from the database according to its primaryId.
     * 
     * @param primaryId The primary key of a Agent.
     * @return The Agent associated with the primaryId that was passed in or
     *         null if not found.
     */
    public static Agent findAgent(Long primaryId) {
        staticMethodLogger().debug("Entering findAgent(primaryId = {})", primaryId);
        if (primaryId == null) {
            staticMethodLogger().debug("Exiting findAgent(): null)");
            return null;
        }
        Agent agent = entityManager().find(Agent.class, primaryId);
        staticMethodLogger().debug("Exiting findAgent(): {})", agent);
        return agent;
    }

    /**
     * Gets a certain subset of Agents based on the range desired.
     * 
     * @param firstResult The beginning of the range of values.
     * @param maxResults The last element of the range of values.
     * @return The collection of Agents based
     */
    public static List<Agent> findAgentEntries(int firstResult, int maxResults) {
        staticMethodLogger().debug("Entering findAgentEntries(firstResult = {}, " +
                "maxResults = {})",
                firstResult, maxResults);
        
        List<Agent> agents = entityManager()
                .createQuery("SELECT o FROM Agent o", Agent.class)
                .setFirstResult(firstResult).setMaxResults(maxResults)
                .getResultList();
        
        staticMethodLogger().debug("Exiting findAgentEntries(): {}", agents);
        return agents;
    }

    /**
     * Persists this object to the persistence context.
     */
    @Transactional
    public void persist() {
        log.debug("Entering persist()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        this.entityManager.persist(this);
        log.debug("Exiting persist()");
    }

    /**
     * Removes this object from the persistence context.
     */
    @Transactional
    public void remove() {
        log.debug("Entering remove()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Agent attached = Agent.findAgent(this.primaryId);
            this.entityManager.remove(attached);
        }
        log.debug("Exiting remove()");
    }

    /**
     * Synchronize the persistence context to the underlying database.
     */
    @Transactional
    public void flush() {
        log.debug("Entering flush()");
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        this.entityManager.flush();
        log.debug("Exiting flush()");
    }

    /**
     * If you call clear, all currently managed objects of the EntityManager
     * will be detached and the status is not synchronized with the database. As
     * long as the objects are not explicitly attached again, they are standard
     * Java objects, whose change does not have any effect on the database.
     */
    @Transactional
    public void clear() {
        log.debug("Entering clear()");
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        this.entityManager.clear();
        log.debug("Exiting clear()");
    }

    /**
     * If this object is detached, the merge() method will merge them back into
     * the EntityManager to become managed again. Note that changes to detached
     * entity objects are not stored in the database.
     * 
     * @return The merged Agent.
     */
    @Transactional
    public Agent merge() {
        log.debug("Entering merge()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        Agent merged = this.entityManager.merge(this);
        this.entityManager.flush();
        log.debug("Exiting merge(): {}", merged);
        return merged;
    }

    /**
     * @return The primary id associated with this Agent.
     */
    public Long getPrimaryId() {
        log.debug("Entering getPrimaryId()");
        log.debug("Exiting getPrimaryId(): {}", primaryId);
        return this.primaryId;
    }

    /**
     * @return The version associated with this Agent.
     */
    public Integer getVersion() {
        log.debug("Entering getVersion()");
        log.debug("Exiting getVersion(): {}", this.version);
        return this.version;
    }

    /**
     * Sets the version of this Agent.
     * 
     * @param version The version of this Agent that you want to set.
     */
    public void setVersion(Integer version) {
        log.debug("Entering setVersion(version = {})", version);
        this.version = version;
        log.debug("Exiting setVersion()");
    }
    
    /**
     * Sets the logger for this class.
     * 
     * @param log The logger for this class.
     */
    @AutowiredLogger
    public void setLog(Logger log) {
        this.log = log;
    }
}
