package gov.hawaii.digitalarchives.hida.core.model.record;
import java.io.Serializable;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.slf4j.Logger;
import org.springbyexample.util.log.AutowiredLogger;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

/**
 * RecordLanguage model class. {@link DigitalRecord} will hold a collection
 * of languages, and this class represents a language. 
 * 
 * @author Keone Hiraide
 */
@Configurable
@Entity
@Table(name = "RECORD_LANGUAGE")
public class RecordLanguage implements Serializable {
    
    /**
     * Autogenerated for this entity to be serializable. Implementing
     * Serializable isn't strictly necessary as far as the JPA specification
     * is concerned. However, it is needed if you're going to use caching or
     * EJB remoting, both of which require objects to be Serializable.
     * Caching is a key component in achieving optimal performance in any
     * JPA application, so implementing the Serializable interface is a good
     * habit to adopt. Note: This was taken from the book titled, 
     * "Spring Persistence with Hibernate", 2010, Fisher and Murphy. 
     */
    private static final long serialVersionUID = 8422038494713854419L;

    /** The Unique Primary Identifier for a RecordLanguage. */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "RECORD_LANGUAGE_ID")
    private Long primaryId;

    /**
     * Specifies the version field or property of an entity class that serves 
     * as its optimistic lock value. The version is used to ensure 
     * integrity when performing the merge operation and for optimistic 
     * concurrency control. 
     */
    @Version
    @Column(name = "VERSION")
    private Integer version;
    
    /**
     * Language that will be contained within a {@link DigitalRecord}.
     */
    @Column(name = "LANGUAGE")
    private String language;
    
     /**
     * Many RecordLanguage objects are associated with a single DigitalRecord 
     * object. A DigitalRecord object's primary key will be used as a foreign 
     * key in this RecordLanguage object/table.
     */
    @ManyToOne(cascade=CascadeType.ALL)
    @JoinColumn(name = "DIGITAL_RECORD_ID")
    private DigitalRecord digitalRecord;
    
    
    
    /**
     * An {@link EntityManager} instance is associated with a persistence 
     * context. A persistence context is a set of entity instances in which 
     * for any persistent entity identity there is a unique entity instance. 
     * Within the persistence context,the entity instances and their life cycle
     * are  managed. The EntityManager API is used to create and remove 
     * persistent entity instances, to find  entities by their primary key, 
     * and to query over entities. As long as an object is attached to an 
     * EntityManager, all changes to the object will be synchronized with 
     * the database automatically (Meaning that this object is attached to the
     * 'persistence context'). 
     */
    @PersistenceContext
    transient EntityManager entityManager;
    
    /** Autowired logger to log this class */
    private transient Logger log = null;
    
    
    
    /**
     * Oracle specifications state that the class must have a public 
     * or protected, no-argument constructor. The class may have other 
     * constructors. 
     * http://docs.oracle.com/javaee/7/tutorial/doc/persistence-intro001.htm
     */
    public RecordLanguage() {
        
    }
    
    
    
    /**
     * Used to create a RecordLanguage object.
     * 
     * @param language       Language that will be contained within 
     *                       a {@link DigitalRecord}.
     * @param digitalRecord  The digitalRecord that will hold this language.
     */
    public RecordLanguage(final String language, final DigitalRecord digitalRecord) {
        Assert.notNull(language, "language cannot be null.");
        Assert.notNull(digitalRecord, "digital record cannot be null.");
        this.language = language;
        this.digitalRecord = digitalRecord;
    }

    
    /**
     * @return  The language in the form of a String for this RecordLanguage.
     */
    public String getLanguage() {
        log.debug("Entering getLanguage()");
        log.debug("Exiting getLanguage(): {}", this.language);
        return this.language;
    }

    
    /**
     * @return The {@link DigitalRecord} instance associated with this
     *         RecordLanguage.
     */
    public DigitalRecord getDigitalRecord() {
        log.debug("Entering getDigitalRecord()");
        log.debug("Exiting getDigitalRecord(): {}", this.digitalRecord);
        return this.digitalRecord;
    }

    
    
    /**
     * A new entity manager is created for every persistence related function. 
     * This pattern is called an “entitymanger-per-request” pattern. 
     * In this model, a request from the client is sent to the server 
     * (where the JPA persistence layer runs), a new EntityManager is opened, 
     * and all database operations are executed in this unit of work. Once the 
     * work has been completed (and the response for the client has been
     * prepared), the persistence context is flushed and closed, as well 
     * as the entity manager object. You would also use a single database 
     * transaction to serve the clients request. The relationship between 
     * the two is one-to-one and this model is a perfect fit for many 
     * applications.
     * 
     * http://docs.jboss.org/hibernate/entitymanager/ 
     * 
     * @return A new EntityManager to do database operations.
     */
    public static final EntityManager entityManager() {
        staticMethodLogger().debug("Entering entityManager()");
        EntityManager em = new RecordLanguage().entityManager;
        if (em == null)  {
            String errorMessage = "Entity manager has not been injected "
                    + "(is the Spring Aspects JAR configured as an AJC/AJDT aspects library?'";
            staticMethodLogger().error(errorMessage);
            throw new IllegalStateException(errorMessage);
        }
        
        staticMethodLogger().debug("Exiting entityManager(): {}", em);
        return em;
    }
    
    /**
     * Used to log static methods of this class. Since
     * Autowired logger cannot be "static", this method allows an 
     * Autowired Logger to be used within static methods.
     * 
     * @return A new logger to do logging operations.
     */
    private static final Logger staticMethodLogger() {
        Logger log = new RecordLanguage().log;
        if (log == null) {
            throw new IllegalStateException("Logger has not been"
                + " injected!");
        }
        return log;
    }

    /**
     * Gets the amount of RecordLanguage objects that are currently 
     * in the database.
     * 
     * @return The amount of RecordLanguage objects that are 
     *         currently in the database.
     */
    public static long countRecordLanguages() {
        staticMethodLogger().debug("Entering countRecordLanguages()");
        long count = entityManager().createQuery("SELECT COUNT(o) FROM RecordLanguage o",
                Long.class).getSingleResult();
        staticMethodLogger().debug("Exiting countRecordLanguages(): {}", count);
        return count;
    }

    
    
    /**
     * Gets all of the RecordLanguage objects from the database 
     * and puts them in a collection. 
     * 
     * @return The collection of RecordLanguages that are 
     *         in the database.
     */
    public static List<RecordLanguage> findAllRecordLanguages() {
        staticMethodLogger().debug("Entering findAllRecordLanguages()");
        List<RecordLanguage> recordLanguages = entityManager()
                .createQuery("SELECT o FROM RecordLanguage o", RecordLanguage.class)
                .getResultList();
        staticMethodLogger().debug("Exiting findAllRecordLanguages(): {}", recordLanguages);
        return recordLanguages;
    }

    
    
    /**
     * Queries for a RecordLanguage based on its primaryId.
     * 
     * @param primaryId  The long primaryId associated with the 
     *                   RecordLanguage that you want to search the database 
     *                   for.
     * @return  The associated RecordLanguage matching the primaryId you were
     *          searching for, or null if not found.
     */
    public static RecordLanguage findRecordLanguage(Long primaryId) {
        staticMethodLogger().debug("Entering findRecordLanguage(primaryId = {})", primaryId);
        if (primaryId == null) {
            staticMethodLogger().debug("Exiting findRecordLanguage(): null)");
            return null;
        }
        RecordLanguage recordLanguage = entityManager().find(RecordLanguage.class, primaryId);
        staticMethodLogger().debug("Exiting findRecordLanguage(): {})", recordLanguage);
        return recordLanguage;
    }

    
    

    /**
     * Gets a certain subset of RecordLanguages based 
     * on the range desired.
     * 
     * @param firstResult  The beginning of the range of values.
     * @param maxResults   The last element of the range of values.
     * @return             The collection of RecordLanguages based 
     *                     on the range desired. 
     */
    public static List<RecordLanguage> findRecordLanguageEntries(int firstResult, int maxResults) {
        staticMethodLogger().debug("Entering findRecordLanguageEntries(firstResult = {}, " +
                "maxResults = {})",
                firstResult, maxResults);
        
        List<RecordLanguage> recordLanguages = entityManager()
                .createQuery("SELECT o FROM RecordLanguage o", RecordLanguage.class)
                .setFirstResult(firstResult).setMaxResults(maxResults)
                .getResultList();
        
        staticMethodLogger().debug("Exiting findRecordLanguageEntries(): {}", recordLanguages);
        return recordLanguages;
    }

    
    
    /**
     * Persists this object to the persistence context. 
     */
    @Transactional
    public void persist() {
        log.debug("Entering persist()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        this.entityManager.persist(this);
        log.debug("Exiting persist()");
    }

    
    
    /**
     * Removes this object from the persistence context. 
     */
    @Transactional
    public void remove() {
        log.debug("Entering remove()");
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            RecordLanguage attached = RecordLanguage.findRecordLanguage(this.primaryId);
            this.entityManager.remove(attached);
        }
        log.debug("Exiting remove()");
    }

    
    
    /**
     * Synchronize the persistence context to the underlying database. 
     */
    @Transactional
    public void flush() {
        log.debug("Entering flush()");
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        this.entityManager.flush();
        log.debug("Exiting flush()");
    }

    
    
    /**
     * If you call clear, all currently managed objects of the EntityManager 
     * will be detached and the status is not synchronized with the database. 
     * As long as the objects are not explicitly attached again, they are 
     * standard Java objects, whose change does not have any effect on 
     * the database.
     */
    @Transactional
    public void clear() {
        log.debug("Entering clear()");
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        this.entityManager.clear();
        log.debug("Exiting clear()");
    }

    
    
    /**
     * If this object is detached, the merge() method will merge them back into
     * the EntityManager to become managed again. Note that changes to detached
     * entity objects are not stored in the database.
     * 
     * @return The merged RecordLanguage.
     */
    @Transactional
    public RecordLanguage merge() {
        if (this.entityManager == null) 
            this.entityManager = entityManager();
        RecordLanguage merged = this.entityManager.merge(this);
        this.entityManager.flush();
        log.debug("Exiting merge(): {}", merged);
        return merged;
    }

    
    
    /**
     *  Assists in implementing Object.toString() methods using reflection.
     *  This class uses reflection to determine the fields to append. Because 
     *  these fields are usually private, the class changes the visibility of 
     *  the fields. This will fail under a security manager,
     *  unless the appropriate permissions are set up correctly. 
     */
    @Override
    public String toString() {
        log.debug("Entering toString()");
        String toString = ReflectionToStringBuilder.toString(this,
                ToStringStyle.SHORT_PREFIX_STYLE);
        log.debug("Exiting toString(): {}", toString);
        return toString;
    }


    
    /**
     * @return The ID of this RecordLanguage.
     */
    public Long getPrimaryId() {
        log.debug("Entering getPrimaryId()");
        log.debug("Exiting getPrimaryId(): {}", this.primaryId);
        return this.primaryId;
    }



    /**
     * Gets the version of this RecordLanguage.
     * 
     * @return  The version of this RecordLanguage.
     */
    public Integer getVersion() {
        log.debug("Entering getVersion()");
        log.debug("Exiting getVersion(): {}", this.version);
        return this.version;
    }

    
    
    /**
     * Sets the version of this RecordLanguage.
     * 
     * @param version  The version of this RecordLanguage.
     */
    public void setVersion(Integer version) {
        log.debug("Entering setVersion(version = {})", version);
        this.version = version;
        log.debug("Exiting setVersion()");
    }
    
    /**
     * Sets the logger for this class.
     * 
     * @param log The logger for this class.
     */
    @AutowiredLogger
    public void setLog(Logger log) {
        this.log = log;
    }
}
