package gov.hawaii.digitalarchives.hida.core.model.accession;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.slf4j.Logger;
import org.springbyexample.util.log.AutowiredLogger;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * A drive encapsulates data about a physical or virtual drive that a set of
 * files were taken from for an {@code Accession}. It is basically the root or
 * a simple tree, where a {@code Drive} contains {@link ManifestVolume}s, which 
 * in turn contains {@link ManifestDirectory}s, and {@link ManifestDirectory}s
 * contain {@link ManifestFile}s.
 * <p>
 * A list of {@code ManifestDrive}s, which ultimate boils down to groups of
 * files, comprises the "manifest" of a the files in an {@link Accession}, as 
 * it appeared on the transferer's machine and its filesystem before they were
 * packaged up into a bag and set to HiDA.
 * 
 * @author Dongie Agnir
 */
@Configurable
@Entity
@Table(name = "MANIFEST_DRIVE")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
public class ManifestDrive implements Serializable {

    /**
     * Autogenerated for this entity to be serializable. Implementing
     * Serializable isn't strictly necessary as far as the JPA specification
     * is concerned. However, it is needed if you're going to use caching or
     * EJB remoting, both of which require objects to be Serializable.
     * Caching is a key component in achieving optimal performance in any
     * JPA application, so implementing the Serializable interface is a good
     * habit to adopt. Note: This was taken from the book titled, 
     * "Spring Persistence with Hibernate", 2010, Fisher and Murphy. 
     */
    private static final long serialVersionUID = 5370725068708268145L;

    /**
     * The primary key of a ManifestDrive.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "MANIFEST_DRIVE_ID")
    private Long primaryId;

    /**
     * Specifies the version field or property of an entity class that serves 
     * as its optimistic lock value. The version is used to ensure integrity 
     * when performing the merge operation and for optimistic concurrency 
     * control.
     */
    @Version
    @Column(name = "VERSION")
    private Integer version;

    /**
     * Serial number associated with this ManifestDrive.
     */
    @Column(name = "SERIAL_NUMBER")
    private String serialNumber;

    /**
     * A ManifestDrive object has many Volumes. A ManifiestDrive object's
     * primary key will be used as a foreign key in the Volume object/table.
     */
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "manifestDrive")
    private List<ManifestVolume> volumes;

    /**
     * Many ManifestDrive objects are associated with a single Accession 
     * object. An Accession object's primary key will be used as a foreign key 
     * in this ManifestDrive object/table.
     */
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "ACCESSION_ID")
    private Accession accession;
    
    /**
     * An {@link EntityManager} instance is associated with a persistence
     * context. A persistence context is a set of entity instances in which for
     * any persistent entity identity there is a unique entity instance. Within
     * the persistence context,the entity instances and their life cycle are
     * managed. The EntityManager API is used to create and remove persistent
     * entity instances, to find entities by their primary key, and to query
     * over entities. As long as an object is attached to an EntityManager, all
     * changes to the object will be synchronized with the database
     * automatically (Meaning that this object is attached to the 'persistence
     * context').
     */
    @PersistenceContext
    transient EntityManager entityManager;
    
    /**
     * AutowiredLogger for logging purposes.
     */
    private transient Logger log = null;

    /**
     * Oracle specifications state that the class must have a public or
     * protected, no-argument constructor. The class may have other
     * constructors.
     * 
     * http://docs.oracle.com/javaee/7/tutorial/doc/persistence-intro001.htm
     */
    public ManifestDrive() {

    }

    /**
     * Creates a ManifestDrive with properly set fields.
     * 
     * @param serialNumber The serial number associated with this 
     *                     ManifestDrive.
     * @param volumes The volumes associated with this ManifestDrive.
     * @param accession The {@link Accession} associated with this 
     *                     ManifestDrive.
     */
    public ManifestDrive(final String serialNumber, List<ManifestVolume> volumes, 
            Accession accession) {
        
        Assert.notNull(serialNumber, "serialNumber cannot be null");
        Assert.hasLength(serialNumber, "serialNumber cannot be empty");
        Assert.notNull(volumes, "volumes cannot be null");
        Assert.notNull(accession, "accession cannot be null");
        
        this.serialNumber = serialNumber;
        this.volumes = volumes;
        this.accession = accession;
    }

    /**
     * @return The serial number associated with this ManifestDrive.
     */
    public String getSerialNumber() {
        //log.debug("Entering getSerialNumber()");
        //log.debug("Exiting getSerialNumber(): {}", this.serialNumber);
        return this.serialNumber;
    }

    /**
     * @return Gets the collection of Volumes associated with this 
     *         ManifestDrive instance.
     */
    public List<ManifestVolume> getVolumes() {
        //log.debug("Entering getVolumes()");
        List<ManifestVolume> volumes = Collections.unmodifiableList(this.volumes);
        //log.debug("Exiting getVolumes(): {}", volumes);
        return volumes;
    }

    /**
     * Assists in implementing Object.toString() methods using reflection. This
     * class uses reflection to determine the fields to append. Because these
     * fields are usually private, the class changes the visibility of the
     * fields. This will fail under a security manager, unless the appropriate
     * permissions are set up correctly.
     */
    @Override
    public String toString() {
        //log.debug("Entering toString()");
        String toString = ReflectionToStringBuilder
                .toString(this,ToStringStyle.SHORT_PREFIX_STYLE);
        //log.debug("Exiting toString(): {}", toString);
        return toString;
    }

    /**
     * @return The accession instance associated with this ManifestDrive.
     */
    public Accession getAccession() {
        //log.debug("Entering getAccession()");
        //log.debug("Exiting getAccession(): {}", this.accession);
        return this.accession;
    }

    /**
     * A new entity manager is created for every persistence related function. 
     * This pattern is called an “entitymanger-per-request” pattern. 
     * In this model, a request from the client is sent to the server 
     * (where the JPA persistence layer runs), a new EntityManager is opened, 
     * and all database operations are executed in this unit of work. Once the 
     * work has been completed (and the response for the client has been
     * prepared), the persistence context is flushed and closed, as well 
     * as the entity manager object. You would also use a single database 
     * transaction to serve the clients request. The relationship between 
     * the two is one-to-one and this model is a perfect fit for many 
     * applications.
     *  
     * http://docs.jboss.org/hibernate/entitymanager/
     *  
     * @return A new EntityManager to do database operations.
     */
    public static final EntityManager entityManager() {
        staticMethodLogger().debug("Entering entityManager()");
        EntityManager em = new ManifestDrive().entityManager;
        if (em == null) {
            String errorMessage = "Throwing IllegalStateException in "
                    + "entityManager(): 'Entity manager has not been injected "
                + "(is the Spring Aspects JAR configured as an AJC/AJDT aspects library?'";
            
            staticMethodLogger().error(errorMessage);
            throw new IllegalStateException(errorMessage);
        }
        staticMethodLogger().debug("Exiting entityManager(): {}", em);
        return em;
    }
    
    /**
     * Used to log static methods of this class. Since Autowired logger cannot 
     * be "static", this method allows an Autowired Logger to be used within 
     * static methods.
     * 
     * @return A new logger to do logging operations.
     */
    private static final Logger staticMethodLogger() {
        Logger log = new ManifestDrive().log;
        if (log == null) {
            throw new IllegalStateException("AutowiredLogger has not been"
                    + " injected!");
        }
        return log;
    }

    /**
     * Gets the amount of ManifestDrive objects that are currently in the
     * database.
     * 
     * @return The amount of ManifestDrive objects that are currently in the
     *         database.
     */
    public static long countManifestDrives() {
        staticMethodLogger().debug("Entering countManifestDrives()");
        long count = entityManager().createQuery("SELECT COUNT(o) FROM ManifestDrive o",
                Long.class).getSingleResult();
        staticMethodLogger().debug("Exiting countManifestDrives(): {}", count);
        return count;
    }

    /**
     * Gets all of the ManifestDrive objects from the database and puts them in
     * a collection.
     * 
     * @return The collection of ManifestDrive objects that are in the
     *         database.
     */
    public static List<ManifestDrive> findAllManifestDrives() {
        staticMethodLogger().debug("Entering findAllManifestDrives()");
        List<ManifestDrive> manifestDrives = entityManager()
                .createQuery("SELECT o FROM ManifestDrive o", ManifestDrive.class)
                .getResultList();
        staticMethodLogger().debug("Exiting findAllManifestDrives(): {}", manifestDrives);
        return manifestDrives;
    }

    /**
     * Gets a ManifestDrive from the database according to its primaryId.
     * 
     * @param  primaryId The primary key of a ManifestDrive.
     * @return The ManifestDrive associated with the id that was passed in or
     *         null if not found.
     */
    public static ManifestDrive findManifestDrive(Long primaryId) {
        staticMethodLogger().debug("Entering findManifestDrive(primaryId = {})", primaryId);
        if (primaryId == null) {
            staticMethodLogger().debug("Exiting findManifestDrive(): null)");
            return null;
        }
        ManifestDrive manifestDirectory = entityManager().find(ManifestDrive.class, primaryId);
        staticMethodLogger().debug("Exiting findManifestDrive(): {})", manifestDirectory);
        return manifestDirectory;
    }

    /**
     * Gets a certain subset of ManifestDrives based on the range desired.
     * 
     * @param firstResult The beginning of the range of values.
     * @param maxResults The last element of the range of values.
     * @return The collection of ManifestDrives based on the range desired.
     */
    public static List<ManifestDrive> findManifestDriveEntries(int firstResult,
            int maxResults) {
        staticMethodLogger().debug("Entering findManifestDriveEntries(firstResult = {}, " +
                "maxResults = {})", firstResult, maxResults);
        
        List<ManifestDrive> manifestDrives = entityManager()
                .createQuery("SELECT o FROM ManifestDrive o", ManifestDrive.class)
                .setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
        
        staticMethodLogger().debug("Exiting findManifestDriveEntries(): {}", manifestDrives);
        return manifestDrives;
    }

    /**
     * Persists this object to the persistence context.
     */
    @Transactional
    public void persist() {
        //log.debug("Entering persist()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        this.entityManager.persist(this);
        //log.debug("Exiting persist()");
    }

    /**
     * Removes this object from the persistence context.
     */
    @Transactional
    public void remove() {
        //log.debug("Entering remove()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ManifestDrive attached = ManifestDrive.findManifestDrive(this.primaryId);
            this.entityManager.remove(attached);
        }
        //log.debug("Exiting remove()");
    }

    /**
     * Synchronize the persistence context to the underlying database.
     */
    @Transactional
    public void flush() {
        //log.debug("Entering flush()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        this.entityManager.flush();
        //log.debug("Exiting flush()");
    }

    /**
     * If you call clear, all currently managed objects of the EntityManager
     * will be detached and the status is not synchronized with the database. 
     * As long as the objects are not explicitly attached again, they are 
     * standard Java objects, whose change does not have any effect on the 
     * database.
     */
    @Transactional
    public void clear() {
        //log.debug("Entering clear()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        this.entityManager.clear();
        //log.debug("Exiting clear()");
    }

    /**
     * If this object is detached, the merge() method will merge them back into
     * the EntityManager to become managed again. Note that changes to detached
     * entity objects are not stored in the database.
     * 
     * @return The merged ManifestDrive.
     */
    @Transactional
    public ManifestDrive merge() {
        //log.debug("Entering merge()");
        if (this.entityManager == null)
            this.entityManager = entityManager();
        ManifestDrive merged = this.entityManager.merge(this);
        this.entityManager.flush();
        //log.debug("Exiting merge(): {}", merged);
        return merged;
    }

    /**
     * Gets the primaryId associated with this ManifestDrive.
     * 
     * @return The primaryId associated with this ManifestDrive.
     */
    public Long getPrimaryId() {
        //log.debug("Entering getPrimaryId()");
        //log.debug("Exiting getPrimaryId(): {}", this.primaryId);
        return this.primaryId;
    }

    /**
     * Gets the version of this ManifestDrive.
     * 
     * @return The version of this ManifestDrive.
     */
    public Integer getVersion() {
        //log.debug("Entering getVerison()");
        //log.debug("Exiting getVersion(): {}", this.version);
        return this.version;
    }

    /**
     * Sets the version of this ManifestDrive.
     * 
     * @param version The version of this ManifestDrive.
     */
    public void setVersion(Integer version) {
        //log.debug("Entering setVersion(version = {})", version);
        this.version = version;
        //log.debug("Exiting setVersion()");
        
    }
       
    
    /**
     * Sets the logger for this class.
     * 
     * @param log The logger for this class.
     */
    @AutowiredLogger
    public void setLog(Logger log) {
        this.log = log;
    }
}
